PROTOCOL_VERSION = "1.0"

MESSAGE_TYPE_MATCHMAKING_JOIN = "MATCHMAKING_JOIN"
MESSAGE_TYPE_STATE_UPDATE = "STATE_UPDATE"
MESSAGE_TYPE_AGENT_ACTION = "AGENT_ACTION"
MESSAGE_TYPE_AGENT_MSG = "AGENT_MSG"
