[project]
name = "common"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ahsen Kamal", email = "itsahsenkamal@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "requests>=2.33.1",
]

[project.scripts]
common = "common:main"

[build-system]
requires = ["uv_build>=0.10.11,<0.11.0"]
build-backend = "uv_build"
